### ISSUE TITLE
gcloudSshWrapper how to use it properly

### ISSUE THREAD

**Issue by corentinl** [chad-autry/wac-gce-ansible#1]
Hello.

It's not about a real issue here but i'm wondering how to use [gcloudSshWrapper ](https://github.com/chad-autry/wac-gce-ansible/blob/master/gcloudSshWrapper) properly

1 - I'm providing an inventory with <instances_name>ZONE_DELIMITER<zone>
2 - In my ansible playbook I'm specifing the use of the custom gcloudSshWrapper by specifying ansible_ssh_executable: "ssh_wrapper" and set roles to play againstn the GCE instances
3 -  in the ansible log i'm checking that the gcloudSshWrapper is used

But then I have the following error

<my-gce-instance-name> (1, '', 'ERROR: (gcloud.compute.ssh) could not parse resource []\n')
<my-gce-instance-name> Failed to connect to the host via ssh: ERROR: (gcloud.compute.ssh) could not parse resource []

The error is a bit cryptic to me. Is there any error in the gcloud compute ssh command line itself or is it the command args that are well parsed and transmitted to the gcloud compute ssh command

Thank you

**Comment by chad-autry** [comment]
It is <instance_name>ZONE_DELIMITER<zone_name>, double quotes around ZONE_DELIMITER might be required. The inventory file templated by the docker entrypoint https://github.com/chad-autry/wac-gce-ansible/blob/master/inventory.gcp.yml.template does some work to set up up instance names returned for dynamic inventory.
